version: "3.7"

services:

  php-apache:
    image: webdevops/php-apache
    links:
      - "mariadb"
    ports:
      - 8080:80
    volumes:
      - "./:/app:z"
    environment:
      - PMA_ARBITRARY=1
      - PHP_DISPLAY_ERRORS=On
      - WEB_DOCUMENT_ROOT=/app/public
    restart: always

  mariadb:
    image: mariadb:10.4
    ports:
      - 3306:3306
    volumes:
      - mariadb-vol:/var/lib/mysql:z
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - "mariadb"
    ports:
      - 8081:80
    volumes:
      - pma-vol:/var/lib/mysql:z
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=mariadb
    restart: always



volumes:
  mariadb-vol:
  pma-vol:
